### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo3664888480'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2240 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Review by soSkumar — APPROVED** [review]

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2056361547'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2240 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo1510227158'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2135 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2201502454'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2160 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2547284180'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2155 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2241521238'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2160 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo857122367'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2220 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2453894747'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2090 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo3335170938'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2240 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo1553838282'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2240 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo1457853733'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2095 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Review by neetuoncehub — APPROVED** [review]

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo1078794886'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 1865 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo1236096730'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2045 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Review by Vandna1 — APPROVED** [review]

**Review by so-ravindra — APPROVED** [review]

**Review by vaibhavso — APPROVED** [review]

**Review by ApoorvaSrivastava — APPROVED** [review]

**Review by sampada-ojha — APPROVED** [review]

**Review by SO-ashusrivastava — APPROVED** [review]

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359857976 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359779959 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2360119876 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359958372 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359973181 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359829539 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359669066 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359845507 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359819981 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359796955 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359857976 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359779959 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2360119876 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359958372 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359973181 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359829539 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359669066 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359845507 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359819981 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359796955 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by UpenderOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359857976 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359779959 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2360119876 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359958372 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359973181 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359829539 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359669066 "Approved")*, *[UpenderOH](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2360165255 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359845507 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359819981 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1268#pullrequestreview-2359796955 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
