### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
@ushankar208: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | f890af4493d04610709d91e0eff30e8a806fb0f9 | [link](http://jenkinsx.onceplatform.com/namespaces/jx/pipelineruns/scheduleonce-once-ui-pr-1004-pr-wwhpt) | `/test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290747778 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290753668 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290747778 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]
Nothing from Team Graphene

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290759308 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290753668 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290747778 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290759308 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290778655 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290753668 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290816976 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290747778 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290759308 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290778655 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290753668 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290816976 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290855562 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290747778 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290759308 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290920084 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290778655 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290753668 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290816976 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290855562 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290747778 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290759308 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290920084 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290778655 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290963424 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290753668 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290816976 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290855562 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290747778 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-vikramsingh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290759308 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290920084 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290778655 "Approved")*, *[oh-vikramsingh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1291094740 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290963424 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290753668 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290816976 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290855562 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290747778 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
@ushankar208: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | f890af4493d04610709d91e0eff30e8a806fb0f9 | [link](http://jenkinsx.onceplatform.com/namespaces/jx/pipelineruns/scheduleonce-once-ui-pr-1004-pr-gshdh) | `/test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by oh-integrations** [comment]
@ushankar208: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | f890af4493d04610709d91e0eff30e8a806fb0f9 | [link](http://jenkinsx.onceplatform.com/namespaces/jx/pipelineruns/scheduleonce-once-ui-pr-1004-pr-dhpkv) | `/test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290759308 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290920084 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290778655 "Approved")*, *[oh-vikramsingh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1291094740 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290963424 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290753668 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290816976 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290855562 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290747778 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290739821 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1004#pullrequestreview-1290722267 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
@ushankar208: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | f890af4493d04610709d91e0eff30e8a806fb0f9 | [link](http://jenkinsx.onceplatform.com/namespaces/jx/pipelineruns/scheduleonce-once-ui-pr-1004-pr-976jb) | `/test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
