### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by soSkumar — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224195575 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224195575 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224295385 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224302338 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224195575 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224295385 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224353745 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224302338 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224195575 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224295385 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224353745 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224302338 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224195575 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224295385 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224358859 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224353745 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224302338 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224195575 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224295385 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224368242 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224358859 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by AryanGupt-a — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[AryanGupt-a](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224422940 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224353745 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224302338 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224195575 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224295385 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224368242 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224358859 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224494562 "Approved")*, *[AryanGupt-a](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224422940 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224353745 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224302338 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224195575 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224295385 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224368242 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224358859 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by shubhamistwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224494562 "Approved")*, *[AryanGupt-a](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224422940 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224353745 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224302338 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224195575 "Approved")*, *[shubhamistwalOH](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224606735 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224295385 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224368242 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224015688 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224358859 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1244#pullrequestreview-2224086201 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
