### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235490387 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235490387 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235496289 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Review by SO-jagjeetsingh — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235514032 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235490387 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235531883 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235496289 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235514032 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235534836 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235490387 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235531883 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235496289 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235514032 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235534836 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235541317 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235490387 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235531883 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235496289 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235542800 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235514032 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235534836 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235541317 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235490387 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235531883 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235496289 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Review by UpenderOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235542800 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235602241 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235514032 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235534836 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235541317 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235490387 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235531883 "Approved")*, *[UpenderOH](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235604436 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235496289 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by neetuoncehub — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235542800 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235602241 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235625302 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235514032 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235534836 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235541317 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235490387 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235531883 "Approved")*, *[UpenderOH](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235604436 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235496289 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235542800 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235602241 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235625302 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235514032 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235534836 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235541317 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235490387 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235531883 "Approved")*, *[UpenderOH](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235604436 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235496289 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/990#pullrequestreview-1235487468 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
