### PR TITLE
Merging staging-app2 in to master

### PR DESCRIPTION
**Pull request by Shalini-Nagmoti**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sumitsharma22 — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990142642 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [sumitsharma22]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990142642 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [sumitsharma22]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Review by so-kaushal — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990165531 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990162895 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990142642 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-kaushal,sumitsharma22]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-sdhawan — APPROVED** [review]

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990176846 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990183000 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990165531 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990162895 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990168196 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990142642 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,so-sdhawan,sumitsharma22]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990176846 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990200328 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990183000 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990165531 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990162895 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990168196 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990142642 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990193523 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,so-sdhawan,sumitsharma22,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Raptors

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990176846 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990200328 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990183000 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990215735 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990165531 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990162895 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990168196 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990142642 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990193523 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,so-sdhawan,sumitsharma22,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990176846 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990200328 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990183000 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990215735 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990165531 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990162895 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990168196 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990142642 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990229973 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990193523 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990244711 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990176846 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990200328 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990183000 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990215735 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990165531 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990162895 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990168196 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990142642 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990229973 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990193523 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990244711 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990176846 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990200328 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990183000 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990215735 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990165531 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990162895 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990168196 "Approved")*, *[so-vishusrivastava](https://github.com/scheduleonce/once-ui/pull/919#issuecomment-1142028876 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990142642 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990229973 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/919#pullrequestreview-990193523 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
