### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182443590 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182443590 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182446068 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447080 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182443590 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182446068 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447322 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182462548 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447080 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182443590 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182446068 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]
Nothing from Team Graphene

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182499631 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447322 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182462548 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447080 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182443590 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182446068 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182499631 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447322 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182462548 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182514931 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447080 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182443590 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182446068 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182499631 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182532461 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447322 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182462548 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182514931 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447080 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182443590 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182446068 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
/hold cancel
/approve

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182499631 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182532461 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447322 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182462548 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182514931 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182447080 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182637039 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182554507 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182443590 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/969#pullrequestreview-1182446068 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
