### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ishakathpal**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1743972742 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1743972742 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744072895 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1743972742 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744072895 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744082931 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1743972742 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744086456 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744072895 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744082931 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1743972742 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744086456 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744093773 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744072895 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744082931 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1743972742 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Raptors

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744086456 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744093773 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744102022 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744072895 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744082931 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1743972742 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Review by bharatsinghoh — APPROVED** [review]

**Review by so-abahadur — APPROVED** [review]

**Review by soSkumar — APPROVED** [review]

**Review by neetuoncehub — APPROVED** [review]

**Review by ApoorvaSrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744166607 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744115654 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744128557 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744086456 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744093773 "Approved")*, *[so-abahadur](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744118740 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744114491 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744102022 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744072895 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744119479 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744082931 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1743972742 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-abahadur,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-abahadur — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744166607 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744115654 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744128557 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744086456 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744093773 "Approved")*, *[so-abahadur](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744173071 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744114491 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744102022 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744072895 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744119479 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1744082931 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1095#pullrequestreview-1743972742 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-abahadur,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
