### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by vaibhavso — APPROVED** [review]

**Review by neetuoncehub — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871752062 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871756509 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871752062 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871756509 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762113 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871752062 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871756509 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762652 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762113 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871752062 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871756509 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762652 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871765391 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762113 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871752062 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871767036 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871772225 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871756509 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762652 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871765391 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762113 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871752062 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871767036 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871772225 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871756509 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871798010 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762652 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871765391 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762113 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871752062 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by soSkumar — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871767036 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871772225 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871756509 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871798010 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762652 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871765391 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762113 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871820067 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871752062 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Team Raptors

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871767036 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871772225 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871749639 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871756509 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871798010 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762652 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871765391 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871821770 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871762113 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871820067 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871722017 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1136#pullrequestreview-1871752062 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
