### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045165663 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045207528 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045165663 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Review by oh-rahulsingla — APPROVED** [review]

**Review by neetuoncehub — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045207528 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045261849 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045250060 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045165663 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045240010 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045207528 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045261849 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045250060 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045276590 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045165663 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045240010 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045387378 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045207528 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045261849 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045250060 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045276590 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045165663 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045240010 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045387378 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045207528 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045261849 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045250060 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045398736 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045276590 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045165663 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045240010 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by soSkumar — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045387378 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045207528 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045261849 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045250060 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045398736 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045276590 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045436098 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045165663 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045240010 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045387378 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045207528 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045261849 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045250060 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045619277 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045398736 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045129461 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045276590 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045436098 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045165663 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1183#pullrequestreview-2045240010 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
