### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by SO-ashusrivastava — APPROVED** [review]

**Review by vinaykumar01 — APPROVED** [review]

**Review by soSkumar — APPROVED** [review]

**Review by vaibhavso — APPROVED** [review]

**Review by sampada-ojha — APPROVED** [review]

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843324407 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843274477 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843214343 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843225151 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843266841 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843214855 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843324407 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843274477 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843214343 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843225151 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843266841 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843214855 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Review by raghavaggarwalOH — APPROVED** [review]

**Review by ApoorvaSrivastava — APPROVED** [review]

**Review by bharatsinghoh — APPROVED** [review]

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Raptors.

**Review by faizaloncehub — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843451816 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843471572 "Approved")*, *[faizaloncehub](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843539409 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843324407 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843431028 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843274477 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843214343 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843474991 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843422204 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843225151 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843266841 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1128#pullrequestreview-1843214855 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
