### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Stark.

**Review by ApoorvaSrivastava — APPROVED** [review]
Nothing from Team Graphene

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217060908 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217045861 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217036791 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217062410 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by amanpreetSO — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217078335 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217060908 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217045861 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217036791 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217062410 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217078335 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217060908 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217045861 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217082103 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217036791 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217062410 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217078335 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217060908 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217045861 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217082103 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217094610 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217036791 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217062410 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mohammad-abuzar — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217078335 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217060908 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217045861 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217106738 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217082103 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217094610 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217036791 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217062410 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217078335 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217060908 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217045861 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217106738 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217116789 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217082103 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217110526 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217094610 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217036791 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217062410 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217078335 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217060908 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217045861 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217106738 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217116789 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217082103 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217110526 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217094610 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217036791 "Approved")*, *[sohimanshu](https://github.com/scheduleonce/once-ui/pull/987#issuecomment-1350793346 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217062410 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [amanpreetSO,sohimanshu,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mderazon — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217078335 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217060908 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217045861 "Approved")*, *[mderazon](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217302431 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217106738 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217116789 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217082103 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217110526 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217094610 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217036791 "Approved")*, *[sohimanshu](https://github.com/scheduleonce/once-ui/pull/987#issuecomment-1350793346 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217062410 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [amanpreetSO,mderazon,sohimanshu,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217078335 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217060908 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217045861 "Approved")*, *[mderazon](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217302431 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217106738 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217116789 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217082103 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217110526 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217094610 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217036791 "Approved")*, *[sohimanshu](https://github.com/scheduleonce/once-ui/pull/987#issuecomment-1350793346 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217062410 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/987#pullrequestreview-1217001579 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [amanpreetSO,mderazon,sohimanshu,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
