### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892520686 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892522859 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892520686 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892526224 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892522859 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892520686 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892526224 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892522859 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892520686 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892569517 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892585186 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892526224 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892522859 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892520686 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892569517 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892585186 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892526224 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892643624 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892522859 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892520686 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892569517 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]

**Review by neetuoncehub — APPROVED** [review]

**Review by so-kaushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892585186 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892526224 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892714090 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892675305 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892820713 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892643624 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892522859 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892520686 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892569517 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892585186 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892526224 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892714090 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892836822 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892513978 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892675305 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892820713 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892643624 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892522859 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892520686 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1141#pullrequestreview-1892569517 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
