### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by Shalini-Nagmoti**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **vinaykumar01**
You can assign the PR to them by writing `/assign @vinaykumar01` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **vinaykumar01**
You can assign the PR to them by writing `/assign @vinaykumar01` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]
Nothing from Team Graphene

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **vinaykumar01**
You can assign the PR to them by writing `/assign @vinaykumar01` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352854 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352854 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123357801 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by nrathour — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123381221 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123380854 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352854 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123357801 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123381221 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123380854 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352854 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123357801 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123381221 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123380854 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352854 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123381542 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123357801 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by saxenarajat** [comment]
We didn't release a stable build for this beta release. **Please do not merge this into master.**

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Stark

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123381221 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123380854 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352854 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123381542 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123357801 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123384768 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123349418 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123381221 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123380854 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352854 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123381542 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123388326 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123357801 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123384768 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123341683 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/958#pullrequestreview-1123352361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request closed without merging**
