### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/904#pullrequestreview-954610505 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Review by vaibhavso — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/904#pullrequestreview-954621926 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/904#pullrequestreview-954610505 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/904#pullrequestreview-954624821 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/904#pullrequestreview-954621926 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/904#pullrequestreview-954637004 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/904#pullrequestreview-954610505 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/904#pullrequestreview-954624821 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request closed without merging**
