### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by Shalini-Nagmoti**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525899623 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525935542 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525899623 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by neetuoncehub — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525935542 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525942433 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525899623 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525935542 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525942433 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525944380 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525899623 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525935542 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525942433 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525947688 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525944380 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525899623 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525935542 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525942433 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525947688 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525944380 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525955059 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525899623 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525935542 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1526022376 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525942433 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525947688 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525990221 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525944380 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525955059 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525899623 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by UpenderOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525935542 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1526022376 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525942433 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525947688 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525990221 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525944380 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525844314 "Approved")*, *[UpenderOH](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1526049845 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525955059 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1057#pullrequestreview-1525899623 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
