### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352086997 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by Areeb2512 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Areeb2512](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352089912 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352086997 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Areeb2512](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352089912 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352145845 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352086997 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Areeb2512](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352089912 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352192154 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352153318 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352145845 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352086997 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Review by ApoorvaSrivastava — APPROVED** [review]

**Review by neetuoncehub — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352203751 "Approved")*, *[Areeb2512](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352089912 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352192154 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352207278 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352202788 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352153318 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352145845 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352086997 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352203751 "Approved")*, *[Areeb2512](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352089912 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352192154 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352207278 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352215733 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352202788 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352153318 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352145845 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352086997 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Review by SO-jagjeetsingh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352203751 "Approved")*, *[Areeb2512](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352089912 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352192154 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352207278 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352237461 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352215733 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352202788 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352238248 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352153318 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352145845 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352086997 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352203751 "Approved")*, *[Areeb2512](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352089912 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352192154 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352207278 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352237461 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352215733 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352202788 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352084725 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352238248 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352153318 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352145845 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1033#pullrequestreview-1352086997 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
