### PR TITLE
fix: Occasionally, when hovering over elements that contain ouiToolTi…

### PR DESCRIPTION
**Pull request by faizaloncehub**
…ps, an unusual box appears.

### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo3530661898'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 1930 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo3065855648'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 1910 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Review by oh-abhishekverma — APPROVED** [review]

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2157852584'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 1960 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
@faizaloncehub: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | b81ee01b668185eb310855601abd62194750ee4b | [link](http://jenkinsx.onceplatform.com/namespaces/jx/pipelineruns/scheduleonce-once-ui-pr-1223-pr-9j6wg) | `/test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
