### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by vinaykumar01 — APPROVED** [review]

**Review by SO-ashusrivastava — APPROVED** [review]

**Review by soSkumar — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420245451 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420248274 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420231934 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420259277 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420245451 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420248274 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420231934 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420259277 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420245451 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420265374 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420248274 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420231934 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by neetuoncehub — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420280038 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420259277 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420245451 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420265374 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420248274 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420231934 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420310045 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420280038 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420259277 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420245451 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420265374 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420248274 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420231934 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420310045 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420280038 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420317805 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420259277 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420245451 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420265374 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420248274 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420313763 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420231934 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420367731 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420310045 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420280038 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420317805 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420259277 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420245451 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420265374 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420248274 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420313763 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420231934 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420367731 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420310045 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420280038 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420382259 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420317805 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420259277 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420245451 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420265374 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420248274 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420313763 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420231934 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420367731 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420310045 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420280038 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420382259 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420317805 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420259277 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420245451 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420265374 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420248274 "Approved")*, *[ushankar208](https://github.com/scheduleonce/once-ui/pull/1041#issuecomment-1542037940 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420313763 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1041#pullrequestreview-1420231934 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,ushankar208,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
