### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by Shalini-Nagmoti**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **so-kaushal**
You can assign the PR to them by writing `/assign @so-kaushal` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107005858 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1091600385 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107005858 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107008606 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1091600385 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107005858 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107008606 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107009809 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1091600385 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107005858 "Approved")*, *[Shalini-Nagmoti](https://github.com/scheduleonce/once-ui/pull/955#issuecomment-1246620979 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107008606 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107009809 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1091600385 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107005858 "Approved")*, *[Shalini-Nagmoti](https://github.com/scheduleonce/once-ui/pull/955#issuecomment-1246620979 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107008606 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107009809 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107308137 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1091600385 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107005858 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107313979 "Approved")*, *[Shalini-Nagmoti](https://github.com/scheduleonce/once-ui/pull/955#issuecomment-1246620979 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107008606 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107009809 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107308137 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1091600385 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107005858 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107313979 "Approved")*, *[Shalini-Nagmoti](https://github.com/scheduleonce/once-ui/pull/955#issuecomment-1246620979 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107008606 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107316058 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107009809 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107308137 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1091600385 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107005858 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107333469 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107313979 "Approved")*, *[Shalini-Nagmoti](https://github.com/scheduleonce/once-ui/pull/955#issuecomment-1246620979 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107008606 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107316058 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107009809 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107308137 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1091600385 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107567311 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107005858 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107333469 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107313979 "Approved")*, *[Shalini-Nagmoti](https://github.com/scheduleonce/once-ui/pull/955#issuecomment-1246620979 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107008606 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107316058 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107009809 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1107308137 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/955#pullrequestreview-1091600385 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
