### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by AbhinavUM**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **amanpreetso**
You can assign the PR to them by writing `/assign @amanpreetso` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by soSkumar — APPROVED** [review]

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707843386 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707768948 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707843386 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707890356 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707768948 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707843386 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707890356 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707891222 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707768948 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707843386 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707890356 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707891222 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707768948 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707900032 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Raptors

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707843386 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707890356 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707925388 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707891222 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707768948 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707900032 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707843386 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707890356 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707926284 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707925388 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707891222 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707768948 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707900032 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mohammad-abuzar — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1708021259 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707843386 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707890356 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707926284 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707925388 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707891222 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707768948 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707900032 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-vikramsingh — APPROVED** [review]

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1708060134 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1708021259 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707843386 "Approved")*, *[oh-vikramsingh](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1708056340 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707890356 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707926284 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707925388 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707891222 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707768948 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707900032 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1708060134 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1708021259 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707843386 "Approved")*, *[oh-vikramsingh](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1708056340 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707890356 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707926284 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707925388 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707891222 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707768948 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707900032 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1093#pullrequestreview-1707747339 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
