### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2256245679'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2227 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Review by neetuoncehub — APPROVED** [review]

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2602472992'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2292 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo528590037'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 1437 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo1412807971'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 712 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo341844625'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 1767 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo3033505401'...
fatal
* unable to access 'https://github.com/scheduleonce/once-ui/'
* Send failure
* Broken pipe

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo4116039643'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2097 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo1996598779'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2187 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2816015230'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 8449 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo4118572562'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2157 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo1299024892'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2052 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by Jagriti3110 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Jagriti3110](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517112945 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by soSkumar — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Jagriti3110](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517112945 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517124225 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by Vandna1 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Jagriti3110](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517112945 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517124225 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517150327 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Jagriti3110](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517112945 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517161149 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517124225 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517150327 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Jagriti3110](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517112945 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517161149 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517171139 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517124225 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517150327 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-ravindra — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Jagriti3110](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517112945 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517161149 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517171139 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517194676 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517124225 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517150327 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Jagriti3110](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517112945 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517161149 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517171139 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517194676 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517124225 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517150327 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517278087 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Jagriti3110](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517112945 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517303688 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517161149 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517171139 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517194676 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517124225 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517150327 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517278087 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo707755531'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2292 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2965772273'...
error
* RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly
* CANCEL (err 8)
error
* 2122 bytes of body are still expected
fetch-pack
* unexpected disconnect while reading sideband packet
fatal
* early EOF
fatal
* fetch-pack
* invalid index-pack output

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Jagriti3110](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517112945 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517046163 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517303688 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517161149 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517066891 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517171139 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517194676 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517124225 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517087880 "Approved")*, *[Vandna1](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517150327 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1291#pullrequestreview-2517278087 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to create repo client
* error creating a clone
* exit status 128 Cloning into '/var/tmp/gitrepo2493031446'...
fatal
* unable to access 'https://github.com/scheduleonce/once-ui/'
* Could not resolve host
* github.com

**Pull request merged**
