### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494821543 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494821543 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494837091 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by neetuoncehub — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494843359 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494821543 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494837091 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by soSkumar — APPROVED** [review]

**Review by SO-ashusrivastava — APPROVED** [review]

**Review by so-vaibhav — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494843359 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848968 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494821543 "Approved")*, *[so-vaibhav](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494880765 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848592 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494837091 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494893498 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494843359 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848968 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494821543 "Approved")*, *[so-vaibhav](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494880765 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848592 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494837091 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494893498 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494843359 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494910542 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848968 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494821543 "Approved")*, *[so-vaibhav](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494880765 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848592 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494837091 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494893498 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494843359 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494911155 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494910542 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848968 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494821543 "Approved")*, *[so-vaibhav](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494880765 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848592 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494837091 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kaushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494893498 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494843359 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494911155 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494910542 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848968 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494932839 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494821543 "Approved")*, *[so-vaibhav](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494880765 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848592 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494837091 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494893498 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494843359 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494911155 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494910542 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848968 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494932839 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494821543 "Approved")*, *[so-vaibhav](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494880765 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494848592 "Approved")*, *[ushankar208](https://github.com/scheduleonce/once-ui/pull/1053#issuecomment-1604212054 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494790166 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/1053#pullrequestreview-1494837091 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,ushankar208,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
