### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by:

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880217 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880411 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880217 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880411 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880217 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925896733 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kaushal — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880411 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925898901 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880217 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925896733 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sumitsharma22 — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880411 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925898901 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880217 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925900120 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925896733 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Raptors

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880411 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925905835 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925898901 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925880217 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925900120 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/887#pullrequestreview-925896733 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by raghavaggarwalOH** [comment]
LGTM

**Comment by SO-ashusrivastava** [comment]
Looks Good

**Pull request merged**
