### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Stark

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075596219 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075596219 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075610285 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075596219 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075610285 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075611578 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by deepikarana2708 — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075596219 "Approved")*, *[deepikarana2708](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075633007 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075610285 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075611578 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by siddharth-so — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075596219 "Approved")*, *[deepikarana2708](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075633007 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075610285 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[siddharth-so](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075642061 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075611578 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075596219 "Approved")*, *[deepikarana2708](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075633007 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075610285 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075645261 "Approved")*, *[siddharth-so](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075642061 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075611578 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-vaibhav — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075596219 "Approved")*, *[deepikarana2708](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075633007 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075610285 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075645261 "Approved")*, *[siddharth-so](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075642061 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*, *[so-vaibhav](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075660836 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075611578 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075596219 "Approved")*, *[deepikarana2708](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075633007 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075610285 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075645261 "Approved")*, *[siddharth-so](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075642061 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*, *[so-vaibhav](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075660836 "Approved")*, *[ushankar208](https://github.com/scheduleonce/once-ui/pull/953#issuecomment-1217995790 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075611578 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,ushankar208,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sumitsharma22 — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075596219 "Approved")*, *[deepikarana2708](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075633007 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075610285 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573097 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075645261 "Approved")*, *[siddharth-so](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075642061 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075561756 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075573233 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075556796 "Approved")*, *[so-vaibhav](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075660836 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075735146 "Approved")*, *[ushankar208](https://github.com/scheduleonce/once-ui/pull/953#issuecomment-1217995790 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/953#pullrequestreview-1075611578 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,sumitsharma22,ushankar208,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
