### PR TITLE
Hurricanes/reverting 7.0.14 beta

### PR DESCRIPTION
**Pull request by saxenarajat**
This PR reverts the unnecessary changes which are getting picked up every now and then.

### CODE REVIEW

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **nalingarg**
You can assign the PR to them by writing `/assign @nalingarg` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/qa/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-amuk — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[so-amuk](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1146985280 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **nalingarg**
You can assign the PR to them by writing `/assign @nalingarg` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/qa/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by shashitomar — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[shashitomar](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1146989387 "Approved")*, *[so-amuk](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1146985280 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **nalingarg**
You can assign the PR to them by writing `/assign @nalingarg` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/qa/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[shashitomar](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1146989387 "Approved")*, *[so-amuk](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1146985280 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/961#issuecomment-1283621588 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/qa/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[shashitomar](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1146989387 "Approved")*, *[so-amuk](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1146985280 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/961#issuecomment-1283621588 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/qa/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mderazon — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[mderazon](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1147139376 "Approved")*, *[shashitomar](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1146989387 "Approved")*, *[so-amuk](https://github.com/scheduleonce/once-ui/pull/961#pullrequestreview-1146985280 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/961#issuecomment-1283621588 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/qa/OWNERS)~~ [mderazon,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
