### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to switch to ref 
* failed to update local branch qa for repository scheduleonce/once-ui
* failed to run command in dir /var/tmp/gitrepo2351850898
* git, [fetch origin --force qa:qa]
* fatal
* unable to access 'https://github.com/scheduleonce/once-ui/'
* Failure when receiving data from the peer
* exit status 128

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to switch to ref 
* failed to update local branch qa for repository scheduleonce/once-ui
* failed to run command in dir /var/tmp/gitrepo2351850898
* git, [fetch origin --force qa:qa]
* fatal
* unable to access 'https://github.com/scheduleonce/once-ui/'
* Failure when receiving data from the peer
* exit status 128

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to switch to ref 
* failed to update local branch qa for repository scheduleonce/once-ui
* failed to run command in dir /var/tmp/gitrepo2351850898
* git, [fetch origin --force qa:qa]
* fatal
* unable to access 'https://github.com/scheduleonce/once-ui/'
* Failure when receiving data from the peer
* exit status 128

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to switch to ref 
* failed to update local branch qa for repository scheduleonce/once-ui
* failed to run command in dir /var/tmp/gitrepo2351850898
* git, [fetch origin --force qa:qa]
* fatal
* unable to access 'https://github.com/scheduleonce/once-ui/'
* Failure when receiving data from the peer
* exit status 128

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to switch to ref 
* failed to update local branch qa for repository scheduleonce/once-ui
* failed to run command in dir /var/tmp/gitrepo2351850898
* git, [fetch origin --force qa:qa]
* fatal
* unable to access 'https://github.com/scheduleonce/once-ui/'
* Failure when receiving data from the peer
* exit status 128

**Comment by oh-integrations** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository scheduleonce/once-ui for ref 
* failed to switch to ref 
* failed to update local branch qa for repository scheduleonce/once-ui
* failed to run command in dir /var/tmp/gitrepo2351850898
* git, [fetch origin --force qa:qa]
* fatal
* unable to access 'https://github.com/scheduleonce/once-ui/'
* Failure when receiving data from the peer
* exit status 128

**Review by soSkumar — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312284373 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312292539 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312284373 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312292539 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by neetuoncehub — APPROVED** [review]

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312356800 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312284373 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312292539 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312356924 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[neetuoncehub](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312356800 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312284373 "Approved")*, *[soSkumar](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312292539 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/1259#pullrequestreview-2312356924 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Review by bharatsinghoh — APPROVED** [review]

**Review by Vandna1 — APPROVED** [review]

**Review by ApoorvaSrivastava — APPROVED** [review]

**Pull request merged**
