### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ishakathpal**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — DISMISSED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1146892524 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — DISMISSED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1146892524 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1146909289 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1146892524 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1146909289 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — DISMISSED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1146910074 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1146892524 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1146909289 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by saxenarajat** [comment]
@ishakathpal This PR is picking up changes which we do not wish to merge with Master. Please close this.

I have created a new PR #961 to remove the changes from the tree. Let's get it merged first so as to follow the natural flow of the code from team to master.

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by:

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by:

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by:

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mderazon — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147365890 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147365890 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147367003 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147365890 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147369724 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147367003 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]
Nothing from Team Graphene

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147371527 "Approved")*, *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147365890 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147369724 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147367003 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147371527 "Approved")*, *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147365890 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147373545 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147367003 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by nrathour — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147371527 "Approved")*, *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147373822 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147365890 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147373545 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147367003 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147371527 "Approved")*, *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147373822 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147365890 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147397926 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147373545 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147367003 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147371527 "Approved")*, *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147373822 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147365890 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147416001 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147397926 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147373545 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147367003 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147371527 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147438390 "Approved")*, *[mderazon](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147364657 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147373822 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147244195 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147211679 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147365890 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147416001 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147397926 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147373545 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147367003 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/960#pullrequestreview-1147226458 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [mderazon,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — COMMENTED** [review]
Nothing from Heisenberg

**Pull request merged**
