### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by Shalini-Nagmoti**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sonirani**
You can assign the PR to them by writing `/assign @sonirani` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sonirani**
You can assign the PR to them by writing `/assign @sonirani` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-sdhawan — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-sdhawan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-sdhawan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sumitsharma22 — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107716 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-sdhawan,sumitsharma22]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037112726 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107716 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-sdhawan,sumitsharma22]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by nrathour — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037119611 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037112726 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107716 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037123184 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-sdhawan,sumitsharma22,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037119611 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037112726 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107716 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037124998 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037123184 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037119611 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037112726 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037127303 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107716 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037124998 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037123184 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kaushal — APPROVED** [review]

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037119611 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037112726 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037127303 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037153308 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037142891 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107716 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037124998 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037123184 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by aakash-ravi — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[aakash-ravi](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037155029 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037119611 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037112726 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037127303 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037153308 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037142891 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107716 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037124998 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037123184 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[aakash-ravi](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037155029 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037106852 "Approved")*, *[nrathour](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037119611 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037112726 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037127303 "Approved")*, *[Shalini-Nagmoti](https://github.com/scheduleonce/once-ui/pull/932#issuecomment-1183083267 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037153308 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037142891 "Approved")*, *[so-kushal](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037177732 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107384 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037107716 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037124998 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/932#pullrequestreview-1037123184 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
