### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by Shalini-Nagmoti**
### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023022657 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [sumitsharma22]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023022657 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023033723 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [sumitsharma22,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023035709 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023022657 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023033723 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [sumitsharma22,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Review by oh-rahulsingla — APPROVED** [review]

**Review by so-kaushal — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023052652 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023035709 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023043638 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023054628 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023022657 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023033723 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-kaushal,sumitsharma22,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023052652 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023035709 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023043638 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023054628 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023022657 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023033723 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023057986 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-kaushal,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-sdhawan — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023052652 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023035709 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023043638 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023054628 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023060619 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023022657 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023033723 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023057986 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-kaushal,so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Raptors

**Review by mohammad-abuzar — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023156257 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023052652 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023035709 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023043638 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023077091 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023054628 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023060619 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023022657 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023033723 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023057986 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-kaushal,so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023222250 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023156257 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023052652 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023035709 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023043638 "Approved")*, *[Shalini-Nagmoti](https://github.com/scheduleonce/once-ui/pull/925#issuecomment-1169929639 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023077091 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023054628 "Approved")*, *[so-sdhawan](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023060619 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023022657 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023033723 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/once-ui/pull/925#pullrequestreview-1023057986 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fonce-ui).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/once-ui/blob/master/OWNERS)~~ [so-kaushal,so-sdhawan,sumitsharma22,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
